fid_denoise:
  _target_: jamun.callbacks.FIDDenoiseCallback
  sigma_list: [1.0, 0.5, 0.25, 0.1, 0.05, 0.01]
  every_n_epochs: 1
  dloader:
    _target_: torch.utils.data.DataLoader
    dataset:
      _target_: torchvision.datasets.CIFAR10
      root: ${paths.data_path}/cifar10
      train: true
      download: false
      transform:
        _target_: torchvision.transforms.v2.ToImage
    batch_size: 32
    shuffle: false
    num_workers: 0
