_target_: jamun.archs.E3NN_nobonds
_partial_: true
irreps_out: "1x1o"
irreps_hidden: "128x0e + 64x1o + 32x2e"
irreps_sh: "1x0e+1x1o+1x2e"
n_layers: 2
hidden_layer_factory:
  _target_: e3tools.nn.ConvBlock
  _partial_: true
  conv:
    _target_: e3tools.nn.SeparableConv
    _partial_: true
output_head_factory:
  _target_: e3tools.nn.EquivariantMLP
  _partial_: true
  irreps_hidden_list:
    - ${model.arch.irreps_hidden}
