_target_: jamun.model.arch.Ophiuchus
_partial_: true
irreps_out: "1x1e"
irreps_hidden: "64x0e + 64x1e"
irreps_sh: "1x0e + 1x1e"
n_layers: 4
mul_factor: 64
edge_attr_dim: 8
atom_type_embedding_dim: 8
atom_code_embedding_dim: 8
residue_code_embedding_dim: 32
residue_index_embedding_dim: 8
use_residue_sequence_index: false
conv_factory:
  _target_: jamun.e3tools.nn.ConvBlock
  _partial_: true
  conv:
    _target_: jamun.e3tools.nn.Conv
    _partial_: true
    use_torch_compile: true
    torch_compile_kwargs:
        fullgraph: true
        dynamic: true
        options:
          trace.enabled: false
          trace.fx_graph: false
test_equivariance: true