defaults:
  - _self_
  - model: e3ncsm_pretrained
  - batch_sampler: single_measurement_sampler
  - logger: default
  - paths: default
  - hydra: default
  - callbacks: sampler/default
  - experiment: null

float32_matmul_precision: "high"

repeat_init_samples: 1 # enables generating multiple parallel changes per initial sample
num_batches: 2
continue_chain: true

seed: 42
task_name: "sample"
run_group: "dev"
root_dir: "."

sampler:
  _target_: jamun.sampling.Sampler
  _convert_: "partial" # loggers argument must be passed as plain list
  precision: "32-true"
