defaults:
  - _self_
  - model: denoiser_pretrained
  - batch_sampler: single_measurement_sampler
  - logger: default
  - paths: default
  - hydra: default
  - callbacks: sampler/default
  - experiment: null

float32_matmul_precision: "high"

sample_pdb: null
repeat_init_samples: 1
num_batches: 1
continue_chain: true

seed: 42
task_name: "sample"
run_group: "dev"
run_key: ${now:%Y-%m-%d}_${now:%H-%M-%S} # NOTE in DDP this must be set consistently across ranks

sampler:
  _target_: jamun.sampling.Sampler
  _convert_: "partial" # loggers argument must be passed as plain list
  precision: "32-true"
