_target_: jamun.sampling.mcmc.BAOAB
delta: ${delta}
friction: ${friction}
steps: ${num_sampling_steps_per_batch}
save_trajectory: true
cpu_offload: true
verbose: true
inverse_temperature: ${inverse_temperature}
score_fn_clip: ${score_fn_clip}
M: 1.0
burn_in_steps: 0
v_init: "zero"
