program: jamun_train
method: grid
project: jamun
name: conditional_vs_self
metric:
  name: val/loss
  goal: minimize
parameters:
  model.conditioner._target_:
    values:
      - jamun.model.conditioners.PositionConditioner
      - jamun.model.conditioners.SelfConditioner
  data.datamodule.datasets.train.total_lag_time:
    values: [4, 6, 8, 10]
  model.sigma_distribution.sigma:
    values: [0.01, 0.03684031, 0.13572088, 0.5]
command: 
  - ${program}
  - "--config-dir=configs"
  - "experiment=train_test_single_shape_conditional"
  - "++trainer.log_every_n_steps=10"
  - "++trainer.max_epochs=100"
  - "++paths.root_path=/data2/sules/jamun-conditional-runs"
  - ${args_no_hyphens}