program: jamun_sample
method: grid
project: jamun
name: sweep_delta_friction_large_noise
metric:
  name: Jenson-Shannon Divergence vs. Number of Samples for Predicted Trajectory joined
  goal: minimize
parameters:
  delta: 
    values: [0.012, 0.039, 0.066, 0.093, 0.12]
  friction:
    values: [2.52572864, 1.2552661, 0.71334989, 0.36384343, 0.10536052]

command: 
  - ${program}
  - "--config-dir=configs"
  - "experiment=sample_enhanced_conditioning_sweep"
  - "++batch_sampler.mcmc.history_update_frequency=100"
  - ${args_no_hyphens}