program: jamun_train
method: grid
project: jamun
name: conditional_vs_self
metric:
  name: val/loss
  goal: minimize
parameters:
  model.conditioner._target_:
    values:
      - jamun.model.conditioners.PositionConditioner
      - jamun.model.conditioners.SelfConditioner

command: 
  - ${program}
  - "--config-dir=configs"
  - "experiment=train_test_single_shape_conditional_one_traj"
  - "++trainer.log_every_n_steps=10"
  - ${args_no_hyphens}