from typing import Dict, List


class ResidueMetadata:
    """Metadata for residues and atoms."""

    ATOM_TYPES: List[str] = ["C", "O", "N", "F", "S", "Cl"]
    ATOM_CODES: List[str] = ["C", "O", "N", "S", "Cl", "CA", "CB"]
    RESIDUE_CODES: List[str] = [
        #Canoncial amino acids
        "ALA",
        "ARG",
        "ASN",
        "ASP",
        "CYS",
        "GLU",
        "GLN",
        "GLY",
        "HIS",
        "ILE",
        "LEU",
        "LYS",
        "MET",
        "PHE",
        "PRO",
        "SER",
        "THR",
        "TRP",
        "TYR",
        "VAL",
        "ACE",
        "NME",
        # Add noncanonical amino acids and modifications
        "(N->O)Leu",
        "(N->O)Val",
        "(N->O)Val(3-OH)",
        "1-Nal",
        "2-pyridylmethyl_Gly",
        "3-pyridylethyl_Gly",
        "3Pal",
        "Abu",
        "Aib",
        "Ala(indol-2-yl)",
        "Ala(tBu)",
        "Bal",
        "Bn(4-Cl)_Gly",
        "Bn(4-OH)_Gly",
        "Bn_Gly",
        "Cha",
        "Cys(EtO2H)_NH2",
        "Et_Gly",
        "Hph",
        "MeOEt_Gly",
        "Me_Abu",
        "Me_Abu(morpholino)",
        "Me_Ala(indol-2-yl)",
        "Me_Cha",
        "Me_Nle",
        "Me_Tza",
        "Me_dA",
        "Me_dS",
        "Me_dQ",
        "Me_dAbu",
        "Me_dF",
        "Me_dK",
        "Me_dL",
        "Me_dNva",
        "Me_dV",
        "Me_dW",
        "Mono1",
        "Mono100",
        "Mono14",
        "Mono16",
        "Mono2",
        "Mono29",
        "Mono30",
        "Mono31",
        "Mono32",
        "Mono33",
        "Mono34",
        "Mono38",
        "Mono39",
        "Mono4",
        "Mono40",
        "Mono41",
        "Mono42",
        "Mono44",
        "Mono45",
        "Mono48",
        "Mono5",
        "Mono6",
        "Mono67",
        "Mono7",
        "Nal",
        "Nle",
        "Nva(Ph)",
        "PhPr_Gly",
        "Phe(4-F)",
        "Phg",
        "Pr_Gly",
        "Pye",
        "Sar",
        "Ser(Bn)",
        "Ser(tBu)",
        "Sta",
        "Sta(3R,4R)",
        "Tle",
        "Tyr(Me)",
        "Tza",
        "bHph",
        "cHexCH2_Gly",
        "d(N->O)Gly(allyl)",
        "d(N->O)Leu",
        "d(N->O)Val",
        "d(N->O)aIle",
        "dA",
        "dAbu",
        "dAla(indol-2-yl)",
        "dAsn(Me2)",
        "dAsp(pyrrol-1-yl)",
        "dCha",
        "dC",
        "dF",
        "dGln(Me2)",
        "dGlu(OMe)",
        "dI",
        "dK",
        "dL",
        "dNva",
        "dP",
        "dPye",
        "dT",
        "dV",
        "iBu_Gly",
        "meA",
        "meD",
        "meF",
        "meI",
        "meK",
        "meL",
        "meQ",
        "meS",
        "meT",
        "meV",
        "meW",
        "meY",
        "pentyl_Gly",
        "(N->O)Leu",
        "(N->O)Tyr",
        "(N->O)Val",
        "(N->O)Val(3-OH)",
        "(N->O)xiIle",
        "-aze",
        "-mor",
        "-nme2",
        "-pip",
        "-pyrro",
        "2Abz",
        "4Pal",
        "5-Ava",
        "Abu(5-Tet)",
        "Ac3c",
        "Ac5c",
        "Ala(5-Tet)",
        "Ala(O->S)",
        "Ala(cBu)",
        "Ala(cPent)",
        "Ala(cPr)",
        "Aoc(2)",
        "Arg(Me,Me)",
        "Asp(OMe)",
        "Asp(Ph(2-NH2))",
        "Asp_piperidide",
        "Aze",
        "Bal(3-Me)",
        "Bal(d3-CF3)",
        "Bal(d3-EtPh)",
        "Bal(d3-Me)",
        "Bu_Gly",
        "Chg",
        "EtOEt_Gly",
        "Et_Leu",
        "Et_Phe",
        "Et_Phe(4-Me)",
        "GABA",
        "Gln(Me)",
        "Gln(Me2)",
        "Gln(Mes)",
        "Glu(3R-Me)",
        "Glu(OMe)",
        "Glu_NH2",
        "Gly(allyl)",
        "Gly(cBu)",
        "Gly(cPent)",
        "Gly(cPr)",
        "H2NEt_Phe",
        "HOCOCH2_Bal",
        "HOCOCH2_Gly_ol",
        "Hch",
        "Hph(2-Cl)",
        "Hph(3,4-diCl)",
        "Hph(3-Cl)",
        "Hph(4-CF3)",
        "Hph(4-CF3,3,5-diF)",
        "Hph(4-CF3,3-Cl)",
        "Hph(4-Cl)",
        "Hph(4-Me)",
        "Hph(4-tBu)",
        "Hse(Et)",
        "Hyp(Et)",
        "Ile(O->S)",
        "Leu(O->S)",
        "Lys(Ac)",
        "Lys(Cbz)",
        "Lys(Me)",
        "Lys(Me2)",
        "Lys(O->S)",
        "Lys(Tfa)",
        "Lys(iPr)",
        "Me_Bal",
        "Me_Bal(d3-Me)",
        "Me_Bmt(E)",
        "Me_Chg",
        "Me_Gly(cBu)",
        "Me_Gly(cPent)",
        "Me_Gly(cPr)",
        "Me_Hph",
        "Me_Hse(Me)",
        "Me_Lys(Me)",
        "Me_Nva",
        "Me_Nva(F2)",
        "Me_Phe(3-Cl)",
        "Me_Phe(4-Cl)",
        "Me_Phe(4-Me)",
        "Me_Phe(a,b-dehydro)",
        "Me_Ser(Me)",
        "Me_Ser(Pr)",
        "Me_Ser(isoamyl)",
        "Me_Tyr(Me)",
        "Me_dA",
        "Me_dT",
        "Me_dF",
        "Me_dI",
        "Me_dK",
        "Me_dL",
        "Me_dNle",
        "Me_dV",
        "Me_dW",
        "Me_dY",
        "Met(O2)",
        "Mono10",
        "Mono101",
        "Mono102",
        "Mono103",
        "Mono104",
        "Mono105",
        "Mono106",
        "Mono107",
        "Mono108",
        "Mono109",
        "Mono11",
        "Mono110",
        "Mono111",
        "Mono112",
        "Mono113",
        "Mono114",
        "Mono115",
        "Mono116",
        "Mono117",
        "Mono118",
        "Mono119",
        "Mono12",
        "Mono120",
        "Mono121",
        "Mono122",
        "Mono123",
        "Mono124",
        "Mono125",
        "Mono126",
        "Mono127",
        "Mono13",
        "Mono15",
        "Mono17",
        "Mono18",
        "Mono19",
        "Mono20",
        "Mono21-",
        "Mono22-",
        "Mono23",
        "Mono24",
        "Mono25",
        "Mono26",
        "Mono27",
        "Mono28",
        "Mono3",
        "Mono35",
        "Mono36",
        "Mono37",
        "Mono43",
        "Mono46",
        "Mono47",
        "Mono49",
        "Mono50",
        "Mono51",
        "Mono52",
        "Mono53",
        "Mono54",
        "Mono55",
        "Mono56",
        "Mono57",
        "Mono58",
        "Mono59",
        "Mono60",
        "Mono61",
        "Mono62",
        "Mono63",
        "Mono64",
        "Mono65",
        "Mono66",
        "Mono68",
        "Mono69",
        "Mono70",
        "Mono71",
        "Mono72",
        "Mono73",
        "Mono74",
        "Mono75",
        "Mono76",
        "Mono77",
        "Mono78",
        "Mono79",
        "Mono80",
        "Mono81",
        "Mono82",
        "Mono83",
        "Mono84",
        "Mono85",
        "Mono86",
        "Mono87",
        "Mono88",
        "Mono89",
        "Mono9",
        "Mono90",
        "Mono91",
        "Mono92",
        "Mono93",
        "Mono94",
        "Mono95",
        "Mono96",
        "Mono97",
        "Mono98",
        "Mono99",
        "NH2Bu_Gly",
        "Nle(CHF2)",
        "Nle(OH)",
        "Nva",
        "Orn",
        "PhEt_Gly",
        "Phe(3,5-diCl)",
        "Phe(3-CF3)",
        "Phe(3-Cl)",
        "Phe(3-Cl,5-F)",
        "Phe(3-F)",
        "Phe(4-CF3)",
        "Phe(4-Cl)",
        "Phe(4-NO2)",
        "Phe(CHF2)",
        "Phe(O->S)",
        "Pip",
        "Pro(O->S)",
        "Ser(Ac)",
        "Ser(EtNMe2)",
        "Ser(EtOH)",
        "Ser(Me)",
        "Ser(Ph(2-Cl))",
        "Ser(Ph(3-Cl))",
        "Ser(Pr)",
        "Ser(isoamyl)",
        "Ser(tBuOH)",
        "Thr(O->S)",
        "Trp(5-Br)",
        "Trp(6-Br)",
        "Trp(7-Br)",
        "Tyr(3-F)",
        "Tyr(CHF2)",
        "Tyr(O->S)",
        "Val(3-OH)",
        "aMeLeu",
        "ac-",
        "d(N->O)Gly(allyl)",
        "d(N->O)Leu",
        "d(N->O)Val",
        "d(N->O)aIle",
        "d1-Nal",
        "dA",
        "dAla(O->S)",
        "dF",
        "dHyp",
        "dI",
        "dK",
        "dL",
        "dLeu(3R-OH)",
        "dLeu(O->S)",
        "dN",
        "dP",
        "dPhe(3,4-diF)",
        "dPhe(4-F)",
        "dPip",
        "dPro(O->S)",
        "dR",
        "dS",
        "dSer(Me)",
        "dT",
        "dTrp(O->S)",
        "dTyr(bR-OMe)",
        "dV",
        "dW",
        "dY",
        "deca-",
        "glyco-",
        "isoamyl_Gly",
        "meA",
        "meD",
        "meF",
        "meH",
        "meI",
        "meK",
        "meL",
        "meM",
        "meN",
        "meQ",
        "meS",
        "meT",
        "meV",
        "meW",
        "meY",
        "Me_dR",
        "Me_dN",
        "Me_dD",
        "Me_dE",
        "Me_dH",
        "Me_dM",
        "Me_dC",
        "meR",
        "meC",
        "meE",
        "meG",
        "dD",
        "dQ",
        "dE",
        "dH",
        "dM",
        "dP",
    ]

    # One to three letter code mapping
    AA_3CODES: Dict[str, str] = {
        "A": "ALA",
        "R": "ARG",
        "N": "ASN",
        "D": "ASP",
        "C": "CYS",
        "E": "GLU",
        "Q": "GLN",
        "G": "GLY",
        "H": "HIS",
        "I": "ILE",
        "L": "LEU",
        "K": "LYS",
        "M": "MET",
        "F": "PHE",
        "P": "PRO",
        "S": "SER",
        "T": "THR",
        "W": "TRP",
        "Y": "TYR",
        "V": "VAL",
        # Add mappings for noncanonical amino acids
        "1-Nal": "1-Nal",
        "2-pyridylmethyl_Gly": "2-pyridylmethyl_Gly",
        "3-pyridylethyl_Gly": "3-pyridylethyl_Gly",
        "3Pal": "3Pal",
        "Abu": "Abu",
        "Aib": "Aib",
        "Ala(indol-2-yl)": "Ala(indol-2-yl)",
        "Ala(tBu)": "Ala(tBu)",
        "Bal": "Bal",
        "Bn(4-Cl)_Gly": "Bn(4-Cl)_Gly",
        "Bn(4-OH)_Gly": "Bn(4-OH)_Gly",
        "Bn_Gly": "Bn_Gly",
        "Cha": "Cha",
        "Cys(EtO2H)_NH2": "Cys(EtO2H)_NH2",
        "Et_Gly": "Et_Gly",
        "Hph": "Hph",
        "MeOEt_Gly": "MeOEt_Gly",
        "Me_Abu": "Me_Abu",
        "Me_dQ": "Me_dQ",
        "Me_Abu(morpholino)": "Me_Abu(morpholino)",
        "Me_Ala(indol-2-yl)": "Me_Ala(indol-2-yl)",
        "Me_Cha": "Me_Cha",
        "Me_Nle": "Me_Nle",
        "Me_Tza": "Me_Tza",
        "Me_dAbu": "Me_dAbu",
        "Me_dNva": "Me_dNva",
        "Mono1": "Mono1",
        "Mono100": "Mono100",
        "Mono14": "Mono14",
        "Mono16": "Mono16",
        "Mono2": "Mono2",
        "Mono29": "Mono29",
        "Mono30": "Mono30",
        "Mono31": "Mono31",
        "Mono32": "Mono32",
        "Mono33": "Mono33",
        "Mono34": "Mono34",
        "Mono38": "Mono38",
        "Mono39": "Mono39",
        "Mono4": "Mono4",
        "Mono40": "Mono40",
        "Mono41": "Mono41",
        "Mono42": "Mono42",
        "Mono44": "Mono44",
        "Mono45": "Mono45",
        "Mono48": "Mono48",
        "Mono5": "Mono5",
        "Mono6": "Mono6",
        "Mono67": "Mono67",
        "Mono7": "Mono7",
        "Nal": "Nal",
        "Nle": "Nle",
        "Nva(Ph)": "Nva(Ph)",
        "PhPr_Gly": "PhPr_Gly",
        "Phe(4-F)": "Phe(4-F)",
        "Phg": "Phg",
        "Pr_Gly": "Pr_Gly",
        "Pye": "Pye",
        "Sar": "Sar",
        "Ser(Bn)": "Ser(Bn)",
        "Ser(tBu)": "Ser(tBu)",
        "Sta": "Sta",
        "Sta(3R,4R)": "Sta(3R,4R)",
        "Tle": "Tle",
        "Tyr(Me)": "Tyr(Me)",
        "Tza": "Tza",
        "bHph": "bHph",
        "cHexCH2_Gly": "cHexCH2_Gly",
        "dAbu": "dAbu",
        "dAla(indol-2-yl)": "dAla(indol-2-yl)",
        "dAsn(Me2)": "dAsn(Me2)",
        "dAsp(pyrrol-1-yl)": "dAsp(pyrrol-1-yl)",
        "dCha": "dCha",
        "dGln(Me2)": "dGln(Me2)",
        "dGlu(OMe)": "dGlu(OMe)",
        "dNva": "dNva",
        "dPye": "dPye",
        "iBu_Gly": "iBu_Gly",
        "pentyl_Gly": "pentyl_Gly",
        "(N->O)Leu": "(N->O)Leu",
        "(N->O)Val": "(N->O)Val",
        "(N->O)Val(3-OH)": "(N->O)Val(3-OH)",
        "1-Nal": "1-Nal",
        "2-pyridylmethyl_Gly": "2-pyridylmethyl_Gly",
        "3-pyridylethyl_Gly": "3-pyridylethyl_Gly",
        "3Pal": "3Pal",
        "Abu": "Abu",
        "Aib": "Aib",
        "Ala(indol-2-yl)": "Ala(indol-2-yl)",
        "Ala(tBu)": "Ala(tBu)",
        "Bal": "Bal",
        "Bn(4-Cl)_Gly": "Bn(4-Cl)_Gly",
        "Bn(4-OH)_Gly": "Bn(4-OH)_Gly",
        "Bn_Gly": "Bn_Gly",
        "Cha": "Cha",
        "Cys(EtO2H)_NH2": "Cys(EtO2H)_NH2",
        "Et_Gly": "Et_Gly",
        "Hph": "Hph",
        "MeOEt_Gly": "MeOEt_Gly",
        "Me_Abu": "Me_Abu",
        "Me_Abu(morpholino)": "Me_Abu(morpholino)",
        "Me_Ala(indol-2-yl)": "Me_Ala(indol-2-yl)",
        "Me_Cha": "Me_Cha",
        "Me_Nle": "Me_Nle",
        "Me_Tza": "Me_Tza",
        "Me_dA": "Me_dA",
        "Me_dAbu": "Me_dAbu",
        "Me_dF": "Me_dF",
        "Me_dK": "Me_dK",
        "Me_dL": "Me_dL",
        "Me_dNva": "Me_dNva",
        "Me_dV": "Me_dV",
        "Me_dW": "Me_dW",
        "Mono1": "Mono1",
        "Mono100": "Mono100",
        "Mono14": "Mono14",
        "Mono16": "Mono16",
        "Mono2": "Mono2",
        "Mono29": "Mono29",
        "Mono30": "Mono30",
        "Mono31": "Mono31",
        "Mono32": "Mono32",
        "Mono33": "Mono33",
        "Mono34": "Mono34",
        "Mono38": "Mono38",
        "Mono39": "Mono39",
        "Mono4": "Mono4",
        "Mono40": "Mono40",
        "Mono41": "Mono41",
        "Mono42": "Mono42",
        "Mono44": "Mono44",
        "Mono45": "Mono45",
        "Mono48": "Mono48",
        "Mono5": "Mono5",
        "Mono6": "Mono6",
        "Mono67": "Mono67",
        "Mono7": "Mono7",
        "Nal": "Nal",
        "Nle": "Nle",
        "Nva(Ph)": "Nva(Ph)",
        "PhPr_Gly": "PhPr_Gly",
        "Phe(4-F)": "Phe(4-F)",
        "Phg": "Phg",
        "Pr_Gly": "Pr_Gly",
        "Pye": "Pye",
        "Sar": "Sar",
        "Ser(Bn)": "Ser(Bn)",
        "Ser(tBu)": "Ser(tBu)",
        "Sta": "Sta",
        "Sta(3R,4R)": "Sta(3R,4R)",
        "Tle": "Tle",
        "Tyr(Me)": "Tyr(Me)",
        "Tza": "Tza",
        "bHph": "bHph",
        "cHexCH2_Gly": "cHexCH2_Gly",
        "dA": "dA",
        "dAbu": "dAbu",
        "dAla(indol-2-yl)": "dAla(indol-2-yl)",
        "dAsn(Me2)": "dAsn(Me2)",
        "dAsp(pyrrol-1-yl)": "dAsp(pyrrol-1-yl)",
        "dCha": "dCha",
        "dF": "dF",
        "dC": "dC",
        "dGln(Me2)": "dGln(Me2)",
        "dGlu(OMe)": "dGlu(OMe)",
        "dI": "dI",
        "dK": "dK",
        "dL": "dL",
        "dNva": "dNva",
        "dP": "dP",
        "dPye": "dPye",
        "dT": "dT",
        "dV": "dV",
        "iBu_Gly": "iBu_Gly",
        "meA": "meA",
        "meD": "meD",
        "meF": "meF",
        "meI": "meI",
        "meK": "meK",
        "meL": "meL",
        "meS": "meS",
        "meT": "meT",
        "meV": "meV",
        "meW": "meW",
        "meY": "meY",
        "pentyl_Gly": "pentyl_Gly",
        "2Abz": "2Abz",
        "4Pal": "4Pal",
        "5-Ava": "5-Ava",
        "Abu(5-Tet)": "Abu(5-Tet)",
        "Ac3c": "Ac3c",
        "Ac5c": "Ac5c",
        "Ala(5-Tet)": "Ala(5-Tet)",
        "Ala(O->S)": "Ala(O->S)",
        "Ala(cBu)": "Ala(cBu)",
        "Ala(cPent)": "Ala(cPent)",
        "Ala(cPr)": "Ala(cPr)",
        "Aoc(2)": "Aoc(2)",
        "Arg(Me,Me)": "Arg(Me,Me)",
        "Asp(OMe)": "Asp(OMe)",
        "Asp(Ph(2-NH2))": "Asp(Ph(2-NH2))",
        "Asp_piperidide": "Asp_piperidide",
        "Aze": "Aze",
        "Bal(3-Me)": "Bal(3-Me)",
        "Bal(d3-CF3)": "Bal(d3-CF3)",
        "Bal(d3-EtPh)": "Bal(d3-EtPh)",
        "Bal(d3-Me)": "Bal(d3-Me)",
        "Bu_Gly": "Bu_Gly",
        "Chg": "Chg",
        "EtOEt_Gly": "EtOEt_Gly",
        "Et_Leu": "Et_Leu",
        "Et_Phe": "Et_Phe",
        "Et_Phe(4-Me)": "Et_Phe(4-Me)",
        "GABA": "GABA",
        "Gln(Me)": "Gln(Me)",
        "Gln(Me2)": "Gln(Me2)",
        "Gln(Mes)": "Gln(Mes)",
        "Glu(3R-Me)": "Glu(3R-Me)",
        "Glu(OMe)": "Glu(OMe)",
        "Glu_NH2": "Glu_NH2",
        "Gly(allyl)": "Gly(allyl)",
        "Gly(cBu)": "Gly(cBu)",
        "Gly(cPent)": "Gly(cPent)",
        "Gly(cPr)": "Gly(cPr)",
        "H2NEt_Phe": "H2NEt_Phe",
        "HOCOCH2_Bal": "HOCOCH2_Bal",
        "HOCOCH2_Gly_ol": "HOCOCH2_Gly_ol",
        "Hch": "Hch",
        "Hph(2-Cl)": "Hph(2-Cl)",
        "Hph(3,4-diCl)": "Hph(3,4-diCl)",
        "Hph(3-Cl)": "Hph(3-Cl)",
        "Hph(4-CF3)": "Hph(4-CF3)",
        "Hph(4-CF3,3,5-diF)": "Hph(4-CF3,3,5-diF)",
        "Hph(4-CF3,3-Cl)": "Hph(4-CF3,3-Cl)",
        "Hph(4-Cl)": "Hph(4-Cl)",
        "Hph(4-Me)": "Hph(4-Me)",
        "Hph(4-tBu)": "Hph(4-tBu)",
        "Hse(Et)": "Hse(Et)",
        "Hyp(Et)": "Hyp(Et)",
        "Lys(Ac)": "Lys(Ac)",
        "Lys(Cbz)": "Lys(Cbz)",
        "Lys(Me)": "Lys(Me)",
        "Lys(Me2)": "Lys(Me2)",
        "Lys(Tfa)": "Lys(Tfa)",
        "Lys(iPr)": "Lys(iPr)",
        "Me_Bal": "Me_Bal",
        "Me_Bal(d3-Me)": "Me_Bal(d3-Me)",
        "Me_Bmt(E)": "Me_Bmt(E)",
        "Me_Chg": "Me_Chg",
        "Me_Gly(cBu)": "Me_Gly(cBu)",
        "Me_Gly(cPent)": "Me_Gly(cPent)",
        "Me_Gly(cPr)": "Me_Gly(cPr)",
        "Me_Hph": "Me_Hph",
        "Me_Hse(Me)": "Me_Hse(Me)",
        "Me_Lys(Me)": "Me_Lys(Me)",
        "Me_Nva": "Me_Nva",
        "Me_Nva(F2)": "Me_Nva(F2)",
        "Me_Phe(3-Cl)": "Me_Phe(3-Cl)",
        "Me_Phe(4-Cl)": "Me_Phe(4-Cl)",
        "Me_Phe(4-Me)": "Me_Phe(4-Me)",
        "Me_Phe(a,b-dehydro)": "Me_Phe(a,b-dehydro)",
        "Me_Ser(Me)": "Me_Ser(Me)",
        "Me_Ser(Pr)": "Me_Ser(Pr)",
        "Me_Ser(isoamyl)": "Me_Ser(isoamyl)",
        "Me_Tyr(Me)": "Me_Tyr(Me)",
        "Me_dA": "Me_dA",
        "Me_dF": "Me_dF",
        "Me_dI": "Me_dI",
        "Me_dK": "Me_dK",
        "Me_dL": "Me_dL",
        "Me_dNle": "Me_dNle",
        "Me_dV": "Me_dV",
        "Me_dW": "Me_dW",
        "Me_dS": "Me_dS",
        "Me_dT": "Me_dT",
        "Me_dY": "Me_dY",
        "Met(O2)": "Met(O2)",
        "Mono10": "Mono10",
        "Mono101": "Mono101",
        "Mono102": "Mono102",
        "Mono103": "Mono103",
        "Mono104": "Mono104",
        "Mono105": "Mono105",
        "Mono106": "Mono106",
        "Mono107": "Mono107",
        "Mono108": "Mono108",
        "Mono109": "Mono109",
        "Mono11": "Mono11",
        "Mono110": "Mono110",
        "Mono111": "Mono111",
        "Mono112": "Mono112",
        "Mono113": "Mono113",
        "Mono114": "Mono114",
        "Mono115": "Mono115",
        "Mono116": "Mono116",
        "Mono117": "Mono117",
        "Mono118": "Mono118",
        "Mono119": "Mono119",
        "Mono12": "Mono12",
        "Mono120": "Mono120",
        "Mono121": "Mono121",
        "Mono122": "Mono122",
        "Mono123": "Mono123",
        "Mono124": "Mono124",
        "Mono125": "Mono125",
        "Mono126": "Mono126",
        "Mono127": "Mono127",
        "Mono13": "Mono13",
        "Mono15": "Mono15",
        "Mono17": "Mono17",
        "Mono18": "Mono18",
        "Mono19": "Mono19",
        "Mono20": "Mono20",
        "Mono21": "Mono21",
        "Mono22": "Mono22",
        "Mono23": "Mono23",
        "Mono24": "Mono24",
        "Mono25": "Mono25",
        "Mono26": "Mono26",
        "Mono27": "Mono27",
        "Mono28": "Mono28",
        "Mono3": "Mono3",
        "Mono35": "Mono35",
        "Mono36": "Mono36",
        "Mono37": "Mono37",
        "Mono43": "Mono43",
        "Mono46": "Mono46",
        "Mono47": "Mono47",
        "Mono49": "Mono49",
        "Mono50": "Mono50",
        "Mono51": "Mono51",
        "Mono52": "Mono52",
        "Mono53": "Mono53",
        "Mono54": "Mono54",
        "Mono55": "Mono55",
        "Mono56": "Mono56",
        "Mono57": "Mono57",
        "Mono58": "Mono58",
        "Mono59": "Mono59",
        "Mono60": "Mono60",
        "Mono61": "Mono61",
        "Mono62": "Mono62",
        "Mono63": "Mono63",
        "Mono64": "Mono64",
        "Mono65": "Mono65",
        "Mono66": "Mono66",
        "Mono68": "Mono68",
        "Mono69": "Mono69",
        "Mono70": "Mono70",
        "Mono71": "Mono71",
        "Mono72": "Mono72",
        "Mono73": "Mono73",
        "Mono74": "Mono74",
        "Mono75": "Mono75",
        "Mono76": "Mono76",
        "Mono77": "Mono77",
        "Mono78": "Mono78",
        "Mono79": "Mono79",
        "Mono80": "Mono80",
        "Mono81": "Mono81",
        "Mono82": "Mono82",
        "Mono83": "Mono83",
        "Mono84": "Mono84",
        "Mono85": "Mono85",
        "Mono86": "Mono86",
        "Mono87": "Mono87",
        "Mono88": "Mono88",
        "Mono89": "Mono89",
        "Mono9": "Mono9",
        "Mono90": "Mono90",
        "Mono91": "Mono91",
        "Mono92": "Mono92",
        "Mono93": "Mono93",
        "Mono94": "Mono94",
        "Mono95": "Mono95",
        "Mono96": "Mono96",
        "Mono97": "Mono97",
        "Mono98": "Mono98",
        "Mono99": "Mono99",
        "NH2Bu_Gly": "NH2Bu_Gly",
        "Nle(CHF2)": "Nle(CHF2)",
        "Nle(OH)": "Nle(OH)",
        "Nva": "Nva",
        "Orn": "Orn",
        "PhEt_Gly": "PhEt_Gly",
        "Phe(3,5-diCl)": "Phe(3,5-diCl)",
        "Phe(3-CF3)": "Phe(3-CF3)",
        "Phe(3-Cl)": "Phe(3-Cl)",
        "Phe(3-Cl,5-F)": "Phe(3-Cl,5-F)",
        "Phe(3-F)": "Phe(3-F)",
        "Phe(4-CF3)": "Phe(4-CF3)",
        "Phe(4-Cl)": "Phe(4-Cl)",
        "Phe(4-NO2)": "Phe(4-NO2)",
        "Phe(CHF2)": "Phe(CHF2)",
        "Pip": "Pip",
        "Ser(Ac)": "Ser(Ac)",
        "Ser(EtNMe2)": "Ser(EtNMe2)",
        "Ser(EtOH)": "Ser(EtOH)",
        "Ser(Me)": "Ser(Me)",
        "Ser(Ph(2-Cl))": "Ser(Ph(2-Cl))",
        "Ser(Ph(3-Cl))": "Ser(Ph(3-Cl))",
        "Ser(Pr)": "Ser(Pr)",
        "Ser(isoamyl)": "Ser(isoamyl)",
        "Ser(tBuOH)": "Ser(tBuOH)",
        "Trp(5-Br)": "Trp(5-Br)",
        "Trp(6-Br)": "Trp(6-Br)",
        "Trp(7-Br)": "Trp(7-Br)",
        "Tyr(3-F)": "Tyr(3-F)",
        "Tyr(CHF2)": "Tyr(CHF2)",
        "Val(3-OH)": "Val(3-OH)",
        "aMeLeu": "aMeLeu",
        "ac-": "ac-",
        "d1-Nal": "d1-Nal",
        "dA": "dA",
        "dF": "dF",
        "dHyp": "dHyp",
        "dI": "dI",
        "dK": "dK",
        "dL": "dL",
        "dLeu(3R-OH)": "dLeu(3R-OH)",
        "dN": "dN",
        "dP": "dP",
        "dPhe(3,4-diF)": "dPhe(3,4-diF)",
        "dPhe(4-F)": "dPhe(4-F)",
        "dPip": "dPip",
        "dR": "dR",
        "dS": "dS",
        "dSer(Me)": "dSer(Me)",
        "dT": "dT",
        "dTyr(bR-OMe)": "dTyr(bR-OMe)",
        "dV": "dV",
        "dW": "dW",
        "dY": "dY",
        "deca-": "deca-",
        "glyco-": "glyco-",
        "isoamyl_Gly": "isoamyl_Gly",
        "meA": "meA",
        "meD": "meD",
        "meF": "meF",
        "meH": "meH",
        "meI": "meI",
        "meK": "meK",
        "meL": "meL",
        "meM": "meM",
        "meN": "meN",
        "meQ": "meQ",
        "meS": "meS",
        "meT": "meT",
        "meV": "meV",
        "meW": "meW",
        "meY": "meY",
        "Me_dR":"Me_dR",
        "Me_dN":"Me_dN",
        "Me_dC":"Me_dC",
        "Me_dD":"Me_dD",
        "Me_dE":"Me_dE",
        "Me_dH":"Me_dH",
        "Me_dM":"Me_dM",
        "meR":"meR",
        "meC":"meC",
        "meE":"meE",
        "meG":"meG",
        "dD":"dD",
        "dQ":"dQ",
        "dE":"dE",
        "dH":"dH",
        "dM":"dM",
        "dP":"dP",
    }

    # Three to one letter code mapping
    AA_1CODES: Dict[str, str] = {v: k for k, v in AA_3CODES.items()}

CANONICAL_AA = set(list("ARNDCEQGHILKMFPSTWYV"))

def is_modified_amino_acid(residue_name: str) -> bool:
    """Check if a residue name is a modified amino acid."""
    return residue_name not in CANONICAL_AA

def is_nmethyl(residue_name: str) -> bool:
    """
    Check if a residue is N-methylated by looking up the n-methylation column
    in non_canonical_amino_acids.csv.
    """
    import csv
    import os

    csv_path = "/homefs/home/davidsd5/permeability_oracle/src/permeability_oracle/data/CycPeptMPDB_Monomer_combined.csv"
    try:
        with open(csv_path, newline='') as csvfile:
            reader = csv.DictReader(csvfile)
            for row in reader:
                if row['aa'] == residue_name:
                    return row['n-methylation'].strip().lower() == 'true'
    except Exception:
        pass
    return False

def encode_atom_type(atom_type: str) -> int:
    """Encode atom symbol (eg. C) as an integer."""
    if atom_type in ResidueMetadata.ATOM_TYPES:
        return ResidueMetadata.ATOM_TYPES.index(atom_type)
    else:
        return len(ResidueMetadata.ATOM_TYPES)


def encode_atom_code(atom_code: str) -> int:
    """Encode atom code (eg. CA) as an integer."""
    if atom_code in ResidueMetadata.ATOM_CODES:
        return ResidueMetadata.ATOM_CODES.index(atom_code)
    else:
        return len(ResidueMetadata.ATOM_CODES)


def encode_residue(residue_name: str) -> int:
    """Encode residue name as an integer."""
    # if residue_name.startswith("Me+"):
    #     return len(ResidueMetadata.RESIDUE_CODES) + encode_residue(residue_name[len("Me+"):])
    # # Check if the residue name is already in canonical form
    if residue_name in ResidueMetadata.RESIDUE_CODES:
        return ResidueMetadata.RESIDUE_CODES.index(residue_name)
    else:
        raise ValueError(f"Invalid residue name: {residue_name}. Valid names are: {ResidueMetadata.RESIDUE_CODES}")
        return len(ResidueMetadata.RESIDUE_CODES)


def convert_to_three_letter_code(aa: str) -> str:
    """Convert one-letter amino acid code to three-letter code."""
    # if aa.startswith("Me+"):
    #     return "Me+" + convert_to_three_letter_code(aa[len("Me+"):])  # Return the rest of the string after "Me"

    if len(aa) == 1:
        aa = aa.upper()
        if aa not in ResidueMetadata.AA_3CODES:
            raise ValueError(f"Invalid one-letter amino acid code: {aa}")
        return ResidueMetadata.AA_3CODES[aa]
    elif len(aa) == 3:
        if aa not in ResidueMetadata.AA_1CODES.values():
            raise ValueError(f"Invalid three-letter amino acid code: {aa}")
        return aa
    else:
        if aa not in ResidueMetadata.AA_1CODES.values():
            raise ValueError(f"Invalid three-letter amino acid code: {aa}")
        return aa
        #raise ValueError(f"Invalid amino acid code length: {aa}")


def convert_to_three_letter_codes(peptide: str) -> str:
    """Convert peptides with one-letter amino acid codes to peptides with three-letter codes."""
    if "_" in peptide:
        return peptide
    return "_".join([convert_to_three_letter_code(aa) for aa in peptide])


def convert_to_one_letter_code(aa: str) -> str:
    """Convert three-letter amino acid code to one-letter code."""
    aa = aa.upper()
    if len(aa) == 1:
        if aa not in ResidueMetadata.AA_3CODES:
            raise ValueError(f"Invalid one-letter amino acid code: {aa}")
        return aa
    elif len(aa) == 3:
        if aa not in ResidueMetadata.AA_1CODES:
            raise ValueError(f"Invalid three-letter amino acid code: {aa}")
        return ResidueMetadata.AA_1CODES[aa]
    else:
        if aa not in ResidueMetadata.AA_1CODES:
            raise ValueError(f"Invalid amino acid code: {aa}")
        return ResidueMetadata.AA_1CODES[aa]
        #raise ValueError(f"Invalid amino acid code length: {aa}")


def convert_to_one_letter_codes(peptide: str) -> str:
    """Convert peptides with three-letter amino acid codes to peptides with one-letter codes."""
    if "_" not in peptide:
        return peptide
    return "".join([convert_to_one_letter_code(aa) for aa in peptide.split("_")])

#Adding code to check for residue name in RESIDUE_CODES and convert it to the same naming convention as in ResidueMetadata.Cremp_RESIDUE_Mapping
def convert_to_canonical_residue_names(residue_name: str) -> str:
    """Convert a residue name to its canonical form."""
    if residue_name in ResidueMetadata.RESIDUE_CODES:
        return residue_name
    else:
        raise ValueError(f"Invalid residue name: {residue_name}. Valid names are: {ResidueMetadata.RESIDUE_CODES}")